### m 个样本，每个样本 n 个维度：


x 维度为 (m, n_x)   
y 维度为 (m, 1)   
w 维度为(n_x, 1)  
b 维度为(1, 1)  
  
dz 维度为 (m, 1)  
da 维度为 (m, 1)  
dw 维度为 (n_x, 1)  
db 维度为(1, 1)

In [ ]:
import numpy as np

n_x = 2
m = 6

x = np.random.rand(m, n_x)                  # 0~1 之间的随机数
y = np.random.randint(0, 2, size=[m, 1])    # 随机生成整数 0 或 1
w = np.random.randn(n_x, 1)                 # 标准正态分布，取值在 -1 到 1 之间
b = np.random.randn(1, 1)                   # 标准正态分布，取值在 -1 到 1 之间

print(x, "\n")
print(y, "\n")
print(w, "\n")
print(b)

[[0.6929725  0.54490491]
 [0.17233482 0.79117756]
 [0.67084428 0.9819395 ]
 [0.39158889 0.08769787]
 [0.17641988 0.1993875 ]
 [0.42418192 0.51586359]] 

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]] 

[[-0.06486217]
 [ 0.81517147]] 

[[-1.38234696]]


$J=0\ ;\ \mathrm{d}w_1=0\ ;\ \mathrm{d}w_2=0\ ;\ \mathrm{d}b=0$

In [ ]:
# 初始化赋值零这一步无需处理。

### $For\ i=1\ to\ m$

$z^{(i)}=w^Tx^{(i)}+b$

In [ ]:
z = np.dot(x, w) + b

print("x", x.shape)
print("w", w.shape)
print("z", z.shape)

x (6, 2)
w (2, 1)
z (6, 1)


$a^{(i)}=\sigma(z^{(i)})=\frac{1}{1+e^{-x}}$

In [ ]:
a = 1 / (1 + np.exp(-z))

print("z", z.shape)
print("a", a.shape)

z (6, 1)
a (6, 1)


$J \mathrel{+}=-y^{(i)}\log a^{(i)}-(1-y^{(i)})\log(1-a^{(i)})$

In [ ]:
J = - np.dot(y.T, np.log(a)) - np.dot((1 - y).T, np.log(1 - a))

print("y", y.shape)
print("y.T", y.T.shape)
print("a", a.shape)
print("J", J.shape)

y (6, 1)
y.T (1, 6)
a (6, 1)
J (1, 1)


$\mathrm{d}z^{(i)}=a^{(i)}-y^{(i)}$

In [ ]:
dz = a - y


print("a", a.shape)
print("y", y.shape)
print("dz", dz.shape)

a (6, 1)
y (6, 1)
dz (6, 1)


$\mathrm{d}w_1+\!\,=x_1^{(i)}\mathrm{d}z^{(i)}\\\mathrm{d}w_2+\!\,=x_2^{(i)}\mathrm{d}z^{(i)}$

In [ ]:
dw = np.dot(x.T, dz)

print("x.T", x.T.shape)
print("dz", dz.shape)
print("dw", dw.shape)

x.T (2, 6)
dz (6, 1)
dw (2, 1)


$\mathrm{d}b^{(i)}\mathrel+=\mathrm{d}z^{(i)}$

In [ ]:
db = dz.sum().reshape((1, 1)) # 时刻保证向量的形状是确定的

print("dz", dz.shape)
print("db", db.shape)

dz (6, 1)
db (1, 1)


$J\ /\!=m;\ \mathrm{d}w_1\ /\!=m\ ;\ \mathrm{d}w_2\ /\!=m\ ;\ \mathrm{d}b\ /\!=m$

In [ ]:
print("J", J)
print("dw", dw)
print("db", db)

J /= m
dw /= m
db /= m

print()
print("J", J)
print("dw", dw)
print("db", db)

J [[4.6495922]]
dw [[-0.52058671]
 [-0.9129949 ]]
db [[-1.35291088]]

J [[0.77493203]]
dw [[-0.08676445]
 [-0.15216582]]
db [[-0.22548515]]


In [ ]:
alpha = 0.1 # 学习率

print("w", w)
print("b", b)
print()

w = w - alpha * dw
b = b - alpha * db

print("w", w)
print("b", b)

w [[-0.06486217]
 [ 0.81517147]]
b [[-1.38234696]]

w [[-0.05618573]
 [ 0.83038805]]
b [[-1.35979845]]


Loop 以上 n_epoch 次，直至成本函数 J 降（接近）至 0.

