# 向量化编程与 For 循环编程的代码效率比对。

In [2]:
import numpy as np # numpy 是一个非常好用的数据处理库，支持高阶大规模的多维数组与矩阵运算，也针对数组运算提供大量的数学函数。

import time

n = 1000000

a = np.random.rand(n)
b = np.random.rand(n)




(1000000,)

In [12]:
t_start = time.time()
c = np.dot(a, b)
t_end = time.time()

print("向量化计算")
print("结果：", c)
print("用时：", (t_end - t_start) * 1000, "ms")

向量化计算
结果： 250294.4294996784
用时： 0.5831718444824219 ms


In [14]:
c = 0

t_start = time.time()
for i in range(n):
    c += a[i] * b[i]
t_end = time.time()

print("非向量化计算")
print("结果：", c)
print("用时：", (t_end - t_start) * 1000, "ms")

非向量化计算
结果： 250294.42949968815
用时： 164.9620532989502 ms


# numpy 的逐元素计算示例

In [16]:
x = np.array([0, 1, 2, 3, 4])

print(x)

[0 1 2 3 4]


In [17]:
y = x + 1

print(y)

[1 2 3 4 5]


In [19]:
y = np.log(x + 1)

print(y)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [20]:
y = np.exp(x)

print(y)

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [21]:
y = x / 2

print(y)

[0.  0.5 1.  1.5 2. ]


In [22]:
y = x * x

print(y)

[ 0  1  4  9 16]
